### ISSUE TITLE
Wrong explanation about the Exception Interface in docs.

### ISSUE THREAD

**Issue by bhargavcp** [getsentry/develop#1026]
Hello,

I was reading through the Sentry docs and found a page on the Exception Interface (link: https://develop.sentry.dev/sdk/event-payloads/exception/). According to the example, multiple errors in the exception.values list are sorted oldest to newest

Quoting the docs:
```
try:
    raise Exception
except Exception as e:
    raise ValueError from e
```
Exception would be described first in the values list, followed by a description of ValueError.

However, in practice I found that this is not true. The original error is actually last in the values list. I have a React app where I throw  an error from a component under certain conditions which is then caught by the ErrorBoundary component a level above in the tree.

I found that the Error Boundary error is the first in the list followed by the original error thrown from the component which is opposite of what is described in the example.

Or am I missing something and Error Boundary is a unique case where this is not true?

**Comment by AbhiPrasad** [comment]
Hey, sorry for the late reply getting to this. For future questions I recommend opening a issue at https://github.com/getsentry/sentry, those are triaged regularly. 

The error boundary is a unique case where this is not true, we intentionally arranged the order of the errors like this to optimize grouping.
