### ISSUE TITLE
GitHub integration missing callback URL

### ISSUE THREAD

**Issue by aldy505** [getsentry/develop#1254]
`${url-prefix}/extensions/github/setup/` should also be included as one of callback URL, otherwise the app will fail. Specifying only the `${url-prefix}/auth/sso/` would fail the installation.

👇🏻 This works

![image](https://github.com/getsentry/develop/assets/7274326/18e221a4-51a5-45f1-82e0-844ec149520c)

Code in question: https://github.com/getsentry/develop/blob/3402f8228985e501a3bd8d87af72e416df6acf23/src/docs/integrations/github.mdx?plain=1#L20-L26

**Comment by aldy505** [comment]
Another case: https://discord.com/channels/621778831602221064/1235674927265484930/1235887106048397392

**Comment by xHeaven** [comment]
Thanks a lot, this solved the integration issue on my self-hosted instance. Honestly, I would've never figured it out by myself.

**Comment by aldy505** [comment]
Closing since https://github.com/getsentry/develop/pull/1235 has been merged
