### ISSUE TITLE
Breadcrumbs documentation

### ISSUE THREAD

**Issue by sistr22** [getsentry/develop#210]
Would it be possible to add to the breadcrumps documentation any limitations ?
On that page (probably) develop/src/docs/sdk/event-payloads/breadcrumbs.mdx 

Specially: 

- What is the maximum size of a breadcrump message & data ?

- How many breadcrump can be sent per sessions ?

**Comment by marandaneto** [comment]
https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/
