### ISSUE TITLE
Document the User Feedback API and workings

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/develop#218]
We currently have this one note for [User Feedback](https://develop.sentry.dev/sdk/features/#user-feedback). Recently the API was added to more SDKs and to help outside contributors and new SDK developers ramp up, we need a dedicated page describing how to build this.

Relevant PRs:
* https://github.com/getsentry/sentry-cocoa/pull/805
* https://github.com/getsentry/sentry-java/pull/1017
* https://github.com/getsentry/sentry-dotnet/pull/559

Also relevant to write API docs for is `onCrashedLastRun` which is relevant for Desktop and Mobile apps.

* https://github.com/getsentry/sentry-cocoa/pull/808

One suggestion is to link to code blocks (through a git sha instead of `/master` for example) to help see different implementations.

The docs should clarify that [there's an endpoint for it](https://docs.sentry.io/api/projects/submit-user-feedback/), brought up [by @ueman below](https://github.com/getsentry/develop/issues/218#issuecomment-741868064). The general [gist of it is on the comment below](https://github.com/getsentry/develop/issues/218#issuecomment-742748501).

**Comment by ueman** [comment]
There is also this [page](https://docs.sentry.io/api/projects/submit-user-feedback/) which kinda describes how to implement User Feedback.

**Comment by bruno-garcia** [comment]
Thanks for pointing out @ueman. That page describes how to create a user feedback through the web API. For SDKs, we rely on an envelope item, and we send everything (errors, transactions, sessions, attachments and user feedbacks) to the same endpoint (`/envelope`).

I'll add the link to the note so we can make that distinction on the docs.

**Comment by lucas-zimerman** [comment]
`event_id
UUID String, required. The identifier of the event or transaction.

email
String, recommended. The email of the user.

name
String, recommended. The name of the user.

comments
String, recommended. Comments of the user about what happened.`

Those fields are wrong, name is required and not recommended (It used to be optional if I remember)  also email and comments seems to be required.

**Comment by philipphofmann** [comment]
Also, add this to the docs.

Make sure user feedback can only be created with an event id, like we already have it in Cocoa https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/Public/SentryUserFeedback.h#L20 and Java https://github.com/getsentry/sentry-java/blob/753cf991d597ebc1766d15abb1b91125c178db66/sentry/src/main/java/io/sentry/UserFeedback.java#L19.

Also, make sure the event id is also put into the envelope header, see Cocoa: https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryEnvelope.m#L220 and Java https://github.com/getsentry/sentry-java/blob/753cf991d597ebc1766d15abb1b91125c178db66/sentry/src/main/java/io/sentry/SentryClient.java#L242-L252

**Comment by philipphofmann** [comment]
All fields except `eventId` are optional for relay, see https://github.com/getsentry/relay/pull/886

**Comment by untitaker** [comment]
The behavior as mentioned by @lucas-zimerman is now restored as the getsentry/relay#886 PR is deployed.

That one endpoint with org and project slug was unaffected the whole time.
