### ISSUE TITLE
Document valid Span 'op' field

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#242]
context: https://github.com/getsentry/sentry-java/issues/1170

@rhcarvalho @HazAT does it make sense to make `op` an Enum or is it really a plain string? is somewhere documented which ops does our frontend renders nicely? what is used for? etc...

**Comment by rhcarvalho** [comment]
Not an enum, we need this to be free form. Users can define whatever "operation"  means for them.

On the other hand, SDKs auto-instrumented spans do use a few "op" values and those we try to keep consistent, like `http.server` for HTTP servers.

(internal-only, see also https://app.asana.com/0/1143066478782529/1173540715390795/f)

**Comment by marandaneto** [comment]
cool thank you, I'm closing this then.

nothing to be done, just to be sure that we're using `http.server` for HTTP servers.

cc @Tyrrrz @maciejwalkowiak @brustolin
