### ISSUE TITLE
Document Contexts.trace

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#244]
https://develop.sentry.dev/sdk/event-payloads/contexts/

Apparently, it's the same as a [Span](https://develop.sentry.dev/sdk/event-payloads/span/), that's what I learn here https://develop.sentry.dev/sdk/event-payloads/transaction/#contextstrace
if so, it'd be nice to add an Entry to the [Contexts](https://develop.sentry.dev/sdk/event-payloads/contexts/) page and link to the Spans one

@brustolin

**Comment by marandaneto** [comment]
@rhcarvalho could you confirm that? thanks.

**Comment by rhcarvalho** [comment]
Similar fields, but not the same as a span. The trace context contains data about the transaction ("transaction span", "root span" of a tree).

**Comment by marandaneto** [comment]
I see

> A Transaction has to have a specific contexts.trace entry that contains data from the Span.

so Ideally we'd need to document properly what a `Contexts.trace` really is

**Comment by rhcarvalho** [comment]
In terms of fields, `fields-of(transaction) = fields-of(span) + "name"`; I think it would be clearer documenting how to map from a transaction to an event. Each transaction field from its in-memory representation maps to some part of the pre-existing event type.

**Comment by rhcarvalho** [comment]
One specific point that needs clarification is where the `span.data` goes for the root span / transaction.

- Relay doesn't know about `TraceContext.data` nor `Event.data`: 
   - https://github.com/getsentry/relay/blob/0143ba7c2556315a2836acdb3cfc2112167e9edc/relay-general/src/protocol/contexts.rs#L442-L468
   - https://github.com/getsentry/relay/blob/master/relay-general/src/protocol/event.rs#L168-L490
- JS SDK sends data in TraceContext:
    - https://github.com/getsentry/sentry-javascript/blob/e9e1525da6b5a346fc259ab7df19415d73f2647e/packages/tracing/src/span.ts#L290-L302
- Python SDK ignores `span.data` of the root span/transaction (as of writing):
    - https://github.com/getsentry/sentry-python/blob/1d75da5203bdfaa47e920f5d749b85abff5f07f7/sentry_sdk/tracing.py#L543-L553
    - https://github.com/getsentry/sentry-python/blob/1d75da5203bdfaa47e920f5d749b85abff5f07f7/sentry_sdk/tracing.py#L454-L466

Sentry UI can deal with either arbitrary unknown fields in `TraceContext` as well as `Event.Extra`:

![image](https://user-images.githubusercontent.com/88819/107864390-fb2c5d00-6e5b-11eb-8690-4a382fab1341.png)

**Comment by rhcarvalho** [comment]
Note: I was not able to make the UI show data for the root span in the same way that it shows for child spans:

![image](https://user-images.githubusercontent.com/88819/107864588-f8326c00-6e5d-11eb-9ecf-d57954e3a6cf.png)

**Comment by rhcarvalho** [comment]
I see we got a bit side-tracked in the conversation here.

_Copying from https://github.com/getsentry/sentry-cocoa/pull/1065#discussion_r618642798 below_

---

The trace context is just part of the transaction that is not a top-level event field.

See https://github.com/getsentry/sentry-go/blob/57123a409be55f61b1d5a6da93c176c55a399ad0/tracing.go#L313-L352.

The fields are:

```
TraceID
SpanID
ParentSpanID
Op
Description
Status
```

And note that `SpanContext` (as described in the spec as a data bag for spans) != `TraceContext`.

**Comment by marandaneto** [comment]
@rhcarvalho on Java, the `SpanContext` has the addition of 2 fields, `sampled` and `tags`

**Comment by rhcarvalho** [comment]
If Java is sending those in the "trace context" Relay will accept it (as it accepts unknown keys for forward-compatibility) but it has no use, so just wasting bytes.

**Comment by marandaneto** [comment]
https://develop.sentry.dev/sdk/event-payloads/types/#tracecontext
