### ISSUE TITLE
API suggestion for finishing a transaction/span

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#245]
Based on https://develop.sentry.dev/sdk/unified-api/tracing#new-span-and-transaction-classes
to finish a transaction or a span, you need to call `finish` which is meant to be used either if it's a successful or errored transaction.

one needs to:

```
transaction.status = OK
// or
transaction.status = INTERNAL_ERROR

// and
transaction.finish()
```

what's about making it more user friendly:

```
transaction.success() // infers `status = OK` (200)
// or

transaction.error() // infers `status = UNKNOWN` (500)
// or
transaction.error(status = UNKNOWN) // if Language supports default params.
```

it'd be easier to use and also reducing boilerplate.

same applies for spans

@rhcarvalho @bruno-garcia @Tyrrrz @maciejwalkowiak @HazAT @brustolin

**Comment by rhcarvalho** [comment]
The direction for which we have [precedent](https://github.com/getsentry/sentry-javascript/blob/1fb0b4c3f6533c43ead2d2cb3f0dc4bc8a84e544/packages/types/src/span.ts#L99) for is adding optional arguments to `finish` depending on language support.

```
transaction.finish(endTimestamp=ts, status=...)
```

I'd prefer that than adding more methods.

However, not entirely sold on adding arguments either, not as part of the spec, as that seems to be purely a matter of style and different languages/platforms have contradicting styles (e.g. Python = "there is only one obvious way to do things" vs Perl = "there is always multiple ways to do things").

The original example touches on `status`, but then there is also `tags`, `data`, `start time`, possibly more in the future... is the proposal also envisioning shortcuts for all?

**Comment by Tyrrrz** [comment]
dotnet currently has `transaction.Finish(status = ok)`

**Comment by marandaneto** [comment]
> The original example touches on `status`, but then there is also `tags`, `data`, `start time`, possibly more in the future... is the proposal also envisioning shortcuts for all?

no, not really, only the most important ones, and right now, only `status` seems evident to me.
we've also discussed about `transaction.finish(status=...)` and it does make sense, on the JVM world, `success()` and `error()` just makes more sense, but yeah it'd not match every language idiom anyway, thanks

**Comment by marandaneto** [comment]
@rhcarvalho btw this also came up https://github.com/getsentry/sentry-java/issues/1154 which is not totally related to this issue, but kinda helps to avoid a bit of boilerplate in the JVM world.

**Comment by bruno-garcia** [comment]
I have a few reservations about this change:

* I'd prefer not to extend the public API with opinionated methods that have side effect
* If part of the interface, now implementations have to deal with these overloads (wouldn't be a problem if it was extension methods though, maybe more sense in ktx).
* What failure it was is like one of many options. And extending with status isn't going to be clean since `failure(status)` would like also the non-failing status'.
* What constitutes `success` can be extended later (not just the HTTP-like OK).
