### ISSUE TITLE
Decide on running trace sampler callback if parent sampled=true/false

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/develop#264]
If a sampling decision is received by the parent transaction, should the trace sampling callback be invoked? I believe the answer is yes since this is the strategy to drop transactions generally. But we need to communicate well how customers can inspect the parent sampling decision.

@untitaker mentioned the Python SDK sets a sampling context `parent_sampled` key (with 0/1 as value?).
Is this the way to go and if so should we define in the spec and add this to all SDKs?

I suggest we then add a common customer facing documentation that explains how to deal with this. With code samples in each language accessing this information and using it when making the sampling decision

**Comment by Tyrrrz** [comment]
A thought related to this topic:
If the user has set the `TracesSampleRate` to `0` to disable it and hasn't set `TracesSampler` to anything, then their web app may still tracking transactions if they were started from a trace header received in an incoming HTTP request. At least that's how it works in ASP.NET Core right now. Is this a desired behavior?

**Comment by rhcarvalho** [comment]
@bruno-garcia the behavior is documented here: https://develop.sentry.dev/sdk/performance/#sampling

> [...] the following precedence rules should apply:
> 
> 1. If a sampling decision is passed to startTransaction (startTransaction({name: "my transaction", sampled: true})), that decision will be used, regardlesss of anything else
> 2. **If tracesSampler is defined, its decision will be used. It can choose to keep or ignore any parent sampling decision, or use the sampling context data to make its own decision or choose a sample rate for the transaction.**
> 3. If tracesSampler is not defined, but there's a parent sampling decision, the parent sampling decision will be used.
> 4. If tracesSampler is not defined and there's no parent sampling decision, tracesSampleRate will be used.


> ### Sampling Context
> If defined, the tracesSampler callback should be passed a samplingContext object, which should include, at minimum:
>
> - The transactionContext with which the transaction was created
> - **A boolean parentSampled which contains the sampling decision passed down from the parent, if any**
> - Data from an optional customSamplingContext object passed to startTransaction when it is called manually
> - Depending on the platform, other default data may be included. (For example, for server frameworks, it makes sense to include the request object corresponding to the request the transaction is measuring.)

Though we say "boolean", note that the "if any" implies this is a three-state variable: undefined, true, false. So different languages may need to represent this differently, not necessarily using a native boolean type if that only covers `true` and `false`.

**Comment by bruno-garcia** [comment]
This is pretty well described, thanks for pointing it out.
