### ISSUE TITLE
Add some nuance around code review

### ISSUE THREAD

**Issue by jan-auer** [getsentry/develop#284]
Beyond the CoC and contribution guidelines, some of our teams use a set of unwritten conventions for communicating on GitHub. Two that specifically come to mind are:

- If a pull request gets approved and receives comments/suggestions in the same review, then it is generally good to merge as-is. The comments are to be treated as optional and should be applied at the discretion of the author.
- Not all comments/suggestions are equally important. Some are mere opinions, while block approval. To do this, we sometimes use a hint like `nit:` or even the more elaborate LOGAF scale.

Do some of these sound useful to write down and encourage on GH?

**Comment by chadwhitacre** [comment]
> Not all comments/suggestions are equally important. Some are mere opinions, while block approval. To do this, we sometimes use a hint like nit: or even the more elaborate LOGAF scale.

This is already mostly addressed:

> **Distinguish between “requires changes” and “nitpicks”**
>
> - Consider marking a PR as approved if the only requested changes are minor nits, so as not to block the author in another asynchronous review cycle.

**Comment by chadwhitacre** [comment]
Gosh, I think that covers both your points, @jan-auer. I'm going to go ahead and close this out. Feel free to reopen or make a PR against the code review doc if you think it could use some more detail.
