### ISSUE TITLE
Performance API specify behavior of max spans

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/develop#298]
Some edge cases to agree on the behavior:

* Transactions should have a max number of spans. If new spans are added once the max is reached, the SDK should drop them and ideally use the internal logging to help debugging.
  * This is to help avoid a transaction that never finishes, ending up on a OOM or just sluggish performance.

The goal is to avoid that a user error, or an integration error that ends up with a leaked transaction that, doesn't cause a app crash. This is particularly important on long running processes.

Python sends up to 1k spans to the server. To clarify at which point it truncates off, but the goal here is to avoid keeping objects around forever if the transaction is never finished.

**Comment by marandaneto** [comment]
makes sense, we could though offer an option to increase/decrease (eg maxBreadcrumbs) and not take only our magic number into consideration.

another question is, is this number per transaction? what if I have multiple transactions running in parallel, should we tackle this use case too?

**Comment by rhcarvalho** [comment]
Python, JS, Go have `maxSpans` which defaults to 1000. I couldn't find it in the spec now, but the behavior described above is basically the de facto spec.

**Comment by dashed** [comment]
@rhcarvalho If the amount of spans has exceeded `maxSpans`. Would it make sense to generate a new transaction to capture any remaining spans?

**Comment by rhcarvalho** [comment]
@dashed unfortunately that would not work well today, as we don't have a way to stitch together the two transactions. (Maybe that hack is workable with the new trace view... But still breaks the information architecture as it's logically one transaction, not two or more.)

**Comment by bruno-garcia** [comment]
> This is to help avoid a transaction that never finishes, ending up on a OOM or just sluggish performance.

A customer just hit this issue on one of the SDKs.

**Comment by AbhiPrasad** [comment]
Right now if JS and Python this option is hidden under an experiments option: https://github.com/getsentry/sentry-javascript/blob/master/packages/tracing/src/hubextensions.ts#L178

https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/hub.py#L528

Should we promote these to a first class option here?

**Comment by rhcarvalho** [comment]
> Should we promote these to a first class option here?

Considering there's no need to change those right now, I'd rather further investigate proposals like https://github.com/getsentry/develop/pull/385, instead of further solidifying the existing limitations.

The aforementioned proposal, if implemented, would mean that there's no (theoretical) limit to the number of spans in a transaction. A practical and internal limit might still be in-place to protect from abuse and guarantee our product performance and UI usability.
