### ISSUE TITLE
Document how transaction and spans hierarchy work

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#319]
The docs mention that transaction is a hierarchy of spans, but doesn't cover how they are stored. Does each span contain its own list of spans? Or do the spans gets projected onto a planar list inside of the transaction?

source https://github.com/getsentry/develop/issues/221

**Comment by rhcarvalho** [comment]
At the moment they are stored in the transaction as a list, and it is documented at https://develop.sentry.dev/sdk/performance/#new-span-and-transaction-classes

> Transaction Interface
>
> A Transaction internally holds a flat list of child Spans (not a tree structure)
