### ISSUE TITLE
Document measurements

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#327]
### Environment

Document `transaction.measurements` on https://develop.sentry.dev/sdk/event-payloads/transaction/

### Steps to Reproduce

https://develop.sentry.dev/sdk/event-payloads/transaction/

### Expected Result

`transaction.measurements` data structure should be documented

### Actual Result

`transaction.measurements` isn't documented, we have an internal page.

**Comment by bruno-garcia** [comment]
For reference, PR from @dashed for JS: https://github.com/getsentry/sentry-javascript/pull/2909

Internal docs of the feature: https://www.notion.so/sentry/Sentry-Measurements-887646e3922f4ffd9f0ce793e2a1ad54

**Comment by marandaneto** [comment]
already documented.
