### ISSUE TITLE
Uploading binary types with envelopes

### ISSUE THREAD

**Issue by tonymrakovcic** [getsentry/develop#344]
Hello,
I am referring to this document

https://github.com/getsentry/develop/blob/master/src/docs/sdk/envelopes.mdx

I am experiencing an issue, and the docs don't have an example of sending a binary file to sentry via the envelope endpoint.

I am trying to upload a minidump, which is binary, and it seems to not work because of the special characters that break the envelopes header.
No amount or type of escaping helps.
I believe this to be a bug, but since the docs do not have an example of uploading a binary file I am not sure.

Even if only this is the data payload it does not go through, 
```
miniDump = 'MDMP��a�';
{"type":"attachment","length":${miniDump.length}, "content_type":"application/octet-stream","filename":"UE4Minidump.dmp","attachment_type":"event.minidump"}

```

The error is 
``
{
  detail: 'invalid event envelope',
  causes: [ 'missing newline after header or payload' ]
}
``
If you could provide an example of uploading binary files or note if there is an escaping mechanism, that would be truly appreciated.

If you have any questions I am open to them also

**Comment by marandaneto** [comment]
There are examples here https://develop.sentry.dev/sdk/envelopes/#full-examples
Nothing changes, the important part is that `length` should match the correct size.
