### ISSUE TITLE
How to track durations in CLI command

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/develop#365]
Hi, I was directed to ask questions about session duration to this pull request:

Situation: I have a CLI command that I wish to track duration between commands, one command opens something, the other closes something. In this case, the longer period between session is better. Unlike tracking durations of web request fulfillment, I need to track how long the user has a session open, where "open" means they are using the product. Short durations mean that they aren't really using the product.

What I have tried and would like validation of is the following:

```
    const timestamp = new Date()
    if (params.clean) { // this is the end of a session, log the duration to sentry
        const startTimestamp: string = await session.get('timestamp')
        const duration = (timestamp as any) - (new Date(startTimestamp) as any)  // in ms

        if (duration) {
            Sentry.getCurrentHub().startSession({ duration, ignoreDuration: false })
            Sentry.getCurrentHub().endSession()
        }
    } else { // This is the start of the session, set the session timestamp.
        Sentry.getCurrentHub().startSession({ ignoreDuration: true })
        await session.set('timestamp', timestamp.toISOString())
        Sentry.getCurrentHub().endSession()
    }
```
Here, 'clean' means the user is closing a session, otherwise, the session is being opened. We track the start timestamp in our own session object and then calculate the duration from this when the 'clean' is given. 

I have also tried:
```
            Sentry.captureMessage(util.format('%O', { duration: durationSeconds, params, session }))
```
But I am not sure how this would be useful.

Perhaps this is what I need to do: 
```
    if (params.clean) { // this is the end of a session, log the duration to sentry
        const started: string = await session.get('timestamp')
        if (started) {
            const duration = (new Date() as any) - (new Date(started) as any) // in ms
            const sentrySession: SessionContext = {
                sid: randomUUID(),
                init: true,
                //@ts-ignore
                started: started,
                duration,
                status: SessionStatus.Exited,
                ignoreDuration: false,
                //@ts-ignore
                attrs: {
                    release: '@c6o/cli'
                }
            }
            Sentry.getCurrentHub().startSession(sentrySession)
            Sentry.getCurrentHub().endSession()
        }
    } else { // This is the start of the session, set the session timestamp.
        await session.set('timestamp', new Date().toISOString())
    }
```
Will this work to record the duration for our open/clean cycles of usage so that we can visualize the results in a dashboard or in the performance area of the Sentry website?

How should this be done?

_Originally posted by @robblovell in https://github.com/getsentry/develop/issues/323#issuecomment-870121525_

**Comment by rhcarvalho** [comment]
Hi @robblovell, I've moved the conversation here since the question is broad and perhaps not 100% related to the merged PR.

---

> Will this work to record the duration for our open/clean cycles of usage so that we can visualize the results in a dashboard or in the performance area of the Sentry website?
> 
> How should this be done?

The first part seems to be clarifying that:
- Sessions are the mechanism to track Release Health, and they are only available as aggregates. You cannot look into individual sessions in Sentry.
- Transactions and Spans are used to track Performance. Unlike Sessions, you can look at individual transactions (and their child spans) as well as look at aggregate metrics on transaction duration.

Do you need to look into individual "session" durations for your intended use?

**Comment by robblovell** [comment]
The intent here is to find a way to track duration between cli command invocations and report it to sentry in a way that can be visualized. If Spans and Transactions could be used to track across multiple invocations, then it would be useful to know how. Keep in mind that there are two transactions, an open and a close (representing two invocations of the cli). The time between them is reported in the close transaction, and the open transaction duration should be ignored.

**Comment by robblovell** [comment]
An aggregate timing of time between invocations is really what we want. Instead of "Fast response times", we want "Time being used" where longer is better, not shorter as is usually thought about with servers fulfilling requests. We would like to know the average time between open/close invocations as well as long and short times.

**Comment by robblovell** [comment]
Can you point me to how I can set transaction duration and set a label (open/close) to filter on in visualizing the data?

**Comment by robblovell** [comment]
This seems to be the direction I should go.
```
if (params.clean) { // this is the end of a session, log the duration to sentry
        const started: string = await session.get('timestamp')
        if (started) {
            const duration = (new Date() as any) - (new Date(started) as any) // in ms
            const transaction = Sentry.startTransaction({
                op: 'duration',
                name: session.signature,
                startTimestamp: new Date(started).getUTCSeconds()
            })

            await transaction.finish(new Date().getUTCSeconds())
        }
    } else { // This is the start of the session, set the session timestamp.
        await session.set('timestamp', new Date().toISOString())
    }
```

**Comment by robblovell** [comment]
It looks like my timestamps are not right. What is the right format/type to set these to?
```
There was 1 error encountered while processing this event

timestamp: Invalid timestamp (too old)
```
Here: 
```
             await transaction.finish(new Date().getUTCSeconds())
```
And Here:
```
            const transaction = await Sentry.startTransaction({
                op: 'duration',
                name,
                startTimestamp: new Date(started).getUTCSeconds()
            })
```

**Comment by robblovell** [comment]
Here is my final implementation:
```
    if (params.clean) { // this is the end of a session, log the duration to sentry
        const started: string = await session.get('timestamp')
        if (started) {
            const sessionDisplayName: string = await session.get('displayName')
            const name: string = displayName || sessionDisplayName || session.signature
            const duration = (new Date() as any) - (new Date(started) as any) // in ms
            debug('DURATION (Seconds): ', duration/1000)
            debug('Transaction Name: ', name)
            const transaction = await Sentry.startTransaction({
                op: 'duration',
                name,
                //@ts-ignore
                startTimestamp: new Date(started).toISOString()
            })
            //@ts-ignore
            await transaction.finish(new Date().toISOString())
        }
    } else { // This is the start of the session, set the session timestamp.
        await session.set('timestamp', new Date().toISOString())
        if (displayName) {
            debug('Transaction Name Given: ', displayName)
            await session.set('displayName', displayName)
        }
    }
```

**Comment by rhcarvalho** [comment]
> The intent here is to find a way to track duration between cli command invocations and report it to sentry in a way that can be visualized.

I assume you understand this use case is not what Sentry is particularly made for. But I'll try to help anyway.

My suggestion is to use transactions, because those give you more flexibility in terms of exploring the data in Sentry, as well as eventually adding contextual data like tags.

And the complement to that suggestion is to not use sessions, those are meant to report on release health. That is, don't try to mix the two up like in the last snippet.

[`startTimestamp` and `endTimestamp` are both in seconds since the UNIX epoch](https://github.com/getsentry/sentry-javascript/blob/e9e1525da6b5a346fc259ab7df19415d73f2647e/packages/types/src/span.ts#L52-L60).

You only need to save the "last execution time" somewhere, and then call `startTransaction` with that startTimestamp (in seconds since the unix epoch, so you need something like `Date.now()/1000`).
The call to `finish` should not take any arguments and use the current time or, alternatively, use the "current execution time", the time that will be saved till the next run.

Closing as I understand you are in a good direction and probably have it working already.
