### ISSUE TITLE
Document spec around span operations

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/develop#392]
`op` is part of our [Span spec](https://develop.sentry.dev/sdk/event-payloads/span/#attributes), but we don't have a list of used ops anywhere.

In the section where we detail [HTTP Client features](https://develop.sentry.dev/sdk/features/#http-client-integrations) we mention the operation `http.client`, but we don't further elaborate.

In addition with operations breakdown, the product now depends on op values. We should make that clear in the develop docs. We default breakdowns to use [`http`, `db`, `resource`, and `browser` operations](https://github.com/getsentry/sentry/blob/809b7fe54c6f06cc1e4c503cf83ded896472a011/src/sentry/projectoptions/defaults.py#L74), and relay has [logic for reading/using the operation name](https://github.com/getsentry/relay/blob/9fd1a4310ea7f18a09df9f3a772339a546d6e422/relay-general/src/store/normalize/breakdowns.rs#L148)

This issue serves two purposes. First to start formalizing a list of ops that should be used by the sdks and second to track the inclusion of that list in the develop docs somewhere.

**Comment by marandaneto** [comment]
@AbhiPrasad maybe this can be closed now?

**Comment by AbhiPrasad** [comment]
I was going to close it after I sent a #shipped email - but yes it’s in a finished state.

**Comment by AbhiPrasad** [comment]
Closed with https://vanguard.getsentry.net/p/cl8swagig15050ls6tedzqax7 (internal to Sentry employees)
