### ISSUE TITLE
Dont set lastEventId for transactions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#431]
`lastEventId` could be used for reporting a userfeedback, so we cant assign the lastEventId for transactions

Spec PR https://github.com/getsentry/develop/pull/430/files

Have to change in all the SDKs that do it

- [X] Dart

**Comment by marandaneto** [comment]
@maciejwalkowiak can you check the Java SDK, please?
@brustolin the iOS SDK has to change too.
@bruno-garcia .NET SDK as well
@rhcarvalho for Web SDKs
I'm gonna do it for Flutter

**Comment by kamilogorek** [comment]
Web: https://github.com/getsentry/sentry-javascript/pull/3966

**Comment by bruno-garcia** [comment]
The .NET SDK already works as intended. A test to validate the behavior was added: https://github.com/getsentry/sentry-dotnet/pull/1191

**Comment by kamilogorek** [comment]
Go: https://github.com/getsentry/sentry-go/pull/379

**Comment by bruno-garcia** [comment]
Java needs fixing:

Here:
https://github.com/getsentry/sentry-java/blob/d3764bfc97eed22564a1e23ba96fa73ad2685498/sentry/src/main/java/io/sentry/Hub.java#L578
And here:
https://github.com/getsentry/sentry-java/blob/d3764bfc97eed22564a1e23ba96fa73ad2685498/sentry/src/main/java/io/sentry/Hub.java#L149-L150

@maciejwalkowiak can you please help us out here?
