### ISSUE TITLE
Document the idle transaction and waitForChildren behaviour for automatic UI transactions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#493]
Since more SDKs want to implement this, it'd make sense to be documented.
Flutter PR https://github.com/getsentry/sentry-dart/pull/643
It needs to be generic enough since it also depends on the framework.

**Comment by marandaneto** [comment]
cc @denrase

**Comment by AbhiPrasad** [comment]
https://github.com/getsentry/sentry-java/issues/1523#issuecomment-859086196 is a short description of how it is implemented for browser javascript.

**Comment by AbhiPrasad** [comment]
We are experimenting with idle transaction behaviour in JS, see https://github.com/getsentry/sentry-javascript/pull/4531 for more details.

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/develop/pull/766. Duplicate of https://github.com/getsentry/develop/issues/647.
