### ISSUE TITLE
Dev environment: zsh documentation

### ISSUE THREAD

**Issue by robinrendle** [getsentry/develop#51]
I’m getting my dev environment setup and I’m using zsh so the very first step is confusing: 

![Screenshot 2020-06-03 12 40 25](https://user-images.githubusercontent.com/1900676/83681529-6c123a00-a597-11ea-9f93-ebf7320687c5.png)

My familiarity with the differences between zsh/bash are limited to say the least but I feel like I should still be able to setup my env properly. What file should I be updating here? I understand that I need to update `~/.zshrc` with `eval "$(pyenv init -)"` but then how do I reload the command line if I’m using zsh?

**Comment by dcramer** [comment]
Just needs updated to have a zsh example, but you can completely ignore this, as there's only `.zshrc`
