### ISSUE TITLE
Document what's acceptable in signal handlers

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/develop#601]
We should start documenting what we consider acceptable behavior in the signal handlers in sentry-native and sentry-cocoa.

Generally speaking, you must only call into [async safe code in signal handlers](https://man7.org/linux/man-pages/man7/signal-safety.7.html), but we sometimes have to violate this rule for certain features, for example, https://github.com/getsentry/sentry-cocoa/issues/1873.

**Comment by mitsuhiko** [comment]
I would like us to document our policies and recommendations for async safety in signal handlers in the develop docs. Between sentry native and this sdk we have some patterns which are walking a thin line and for future changes it would be good to bring this to paper.

In sentry native the main contributors to async safety were me and @Swatinem.

**Comment by Swatinem** [comment]
Related: there have been a ton of requests to separate the `before_send` hook from a dedicated `on_crash` hook.
The first should run for normal events, the second one for hard crashes in which users can flush log files and all kinds of other stuff :-D
