### ISSUE TITLE
Span Operations Spec

### ISSUE THREAD

**Issue by smeubank** [getsentry/develop#693]
https://www.notion.so/sentry/Set-up-an-audit-for-SDK-consistency-for-span-operations-to-enable-performance-issues-addf02a8fa234dda8acf48d4ff9b8efb#1b58a8e7b0554e3b8a641102dfa1a939

- [x] Present at TSC
- [x] Email relevant teams
- [x] Get alignment on unknowns
- [x] Chatting with Neel about Ruby
- [x] Update develop docs https://github.com/getsentry/develop/pull/694
- [x] Make GH issues across various SDK repos
  - JavaScript https://github.com/getsentry/sentry-javascript/issues/5837
  - React Native - DONE
  - Python https://github.com/getsentry/sentry-python/issues/1643
  - Ruby https://github.com/getsentry/sentry-ruby/issues/1903
  - Laravel https://github.com/getsentry/sentry-laravel/issues/571
  - Dart https://github.com/getsentry/sentry-dart/issues/1022
  - Cocoa - DONE
  - Java https://github.com/getsentry/sentry-java/issues/2261

**Comment by AbhiPrasad** [comment]
To Change:

| SDK             | Old Operation                             | New Operation                                  | Link                                                                                                                                                                  | PR                                                         |
| --------------- | ----------------------------------------- | ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| Browser         |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | resource                                  | resource.other                                 | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/tracing/src/browser/metrics/index.ts#L369                       |                                                            |
|                 | ui.long-task                              | ui.task                                        | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/tracing/src/browser/metrics/index.ts#L56                        |                                                            |
|                 | web.vitals                                | ui.action                                      | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/tracing/src/browser/metrics/index.ts#L224                       |                                                            |
|                 | ui.vue                                    | ui.vue.render                                  | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/vue/src/tracing.ts#L78                                          |                                                            |
| Vue             |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | ui.vue                                    | ui.vue.render                                  | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/vue/src/tracing.ts#L78                                          |                                                            |
| Ember           |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | ember.route.beforeModel                   | ui.ember.route.before_model                    | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/ember/addon/index.ts#L87                                        |                                                            |
|                 | ember.route.afterModel                    | ui.ember.route.after_model                     | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/ember/addon/index.ts#L100                                       |                                                            |
|                 | ember.route.setupController               | ui.ember.route.setup_controller                | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/ember/addon/index.ts#L109                                       |                                                            |
| Serverless Node |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | gcloud.http.<service-name>                | http.client.<service-name>                     | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/google-cloud-http.ts?q=op%3A#L62                 |                                                            |
|                 | gcp.function.event                        | faas.gcp.event                                 | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/gcpfunction/events.ts#L39                        |                                                            |
|                 | gcp.function.cloud_event                  | faas.gcp.cloud_event                           | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/gcpfunction/cloud_events.ts#L37                  |                                                            |
|                 | gcloud.grpc.<service-name>                | grpc.<service-name>                            | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/google-cloud-grpc.ts#L117                        |                                                            |
|                 | gcp.function.http                         | faas.gcp.http                                  | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/gcpfunction/http.ts#L89                          |                                                            |
|                 | aws.request                               | http.client                                    | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/serverless/src/awsservices.ts#L68                               |                                                            |
|                 | awslambda.handler                         | faas.aws.lambda                                | https://github.com/getsentry/sentry-javascript/blob/754248253733163e0c0b932f61d88f4a47b20026/packages/serverless/src/awslambda.ts#L319                                |                                                            |
| Remix           |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | remix.server.documentRequest              | remix.server.document_request                  | https://github.com/getsentry/sentry-javascript/blob/74672a0330126e4c13f6ed5e655ad549ccad5c1e/packages/remix/src/utils/instrumentServer.ts#L119                        |                                                            |
| Node            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | db.grapql                                 | graphql.execute                                | https://github.com/getsentry/sentry-javascript/blob/781485e3777a5a110f8b02fda308be5e05f54576/packages/tracing/src/integrations/node/graphql.ts#L37                    |                                                            |
|                 | db.prisma                                 | db.sql.prisma                                  | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/tracing/src/integrations/node/prisma.ts#L92                     |                                                            |
|                 | express.middleware.<method>               | middleware.express.<method>                    | https://github.com/getsentry/sentry-javascript/blob/f563eae7e032f2b3d71147be922f95d98babdcb1/packages/tracing/src/integrations/node/express.ts#L149                   |                                                            |
|                 | db.graphql.apollo                         | graphql.resolve                                | https://github.com/getsentry/sentry-javascript/blob/e6e89fd080152074acae4ff9fe1965a8f8bff2e0/packages/tracing/src/integrations/node/apollo.ts#L84                     |                                                            |
| Node            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | nextjs.data.server                        | http.server                                    | https://github.com/getsentry/sentry-javascript/blob/12c19d051eca4fcef316ba6ee512f1221ae92ef0/packages/nextjs/src/config/wrappers/wrapperUtils.ts#L98                  | https://github.com/getsentry/sentry-javascript/pull/5830   |
| React Native    |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | app_start_cold                            | app.start.cold                                 | https://github.com/getsentry/sentry-react-native/blob/b6fe2890eedc3c6f66e1f75d5fab6653106ec889/src/js/tracing/reactnativetracing.ts#L291                              | https://github.com/getsentry/sentry-react-native/pull/2487 |
|                 | app_start_warm                            | app.start.warm                                 | https://github.com/getsentry/sentry-react-native/blob/b6fe2890eedc3c6f66e1f75d5fab6653106ec889/src/js/tracing/reactnativetracing.ts#L291                              | https://github.com/getsentry/sentry-react-native/pull/2487 |
| Python          |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | serverless.function                       | faas.aws.lambda                                | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/aws_lambda.py#L143                                   |                                                            |
|                 | aws.request                               | http.client                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/boto3.py#L65                                         |                                                            |
|                 | aws.request.stream                        | http.client.stream                             | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/boto3.py#L95                                         |                                                            |
|                 | celery.submit                             | queue.submit.celery                            | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/celery.py#L106                                       |                                                            |
|                 | celery.task                               | queue.task.celery                              | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/celery.py#L159                                       |                                                            |
|                 | http                                      | http.client                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/httpx.py#L44                                         |                                                            |
|                 | redis                                     | db.redis                                       | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/redis.py#L32                                         |                                                            |
|                 | rq.task                                   | queue.task.rq                                  | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/rq.py#L64                                            |                                                            |
|                 | starlette.middleware                      | middleware.starlette                           | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/starlette.py#L94                                     |                                                            |
|                 | django.view                               | view.django                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/asgi.py#L92                                   |                                                            |
|                 | django.middleware                         | middleware.django                              | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/middleware.py#L91                             |                                                            |
|                 | django.template.render                    | template.render                                | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/templates.py#L69                              |                                                            |
| Ruby            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | delayed_job                               | queue.task.delayed_job                         | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-delayed_job/lib/sentry/delayed_job/plugin.rb#L21                        |                                                            |
|                 | rails.action_cable                        | websocket.server                               | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/action_cable.rb#L34                              |                                                            |
|                 | active_job                                | queue.task.active_job                          | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/active_job.rb#L28                                |                                                            |
|                 | rails.request                             | http.server                                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/capture_exceptions.rb#L20                        |                                                            |
|                 | process_action.action_controller          | view.process_action.action_controller          | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/action_controller_subscriber.rb#L10      |                                                            |
|                 | service_upload.active_storage             | file.service_upload.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_download.active_storage           | file.service_download.active_storage           | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_streaming_download.active_storage | file.service_streaming_download.active_storage | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_download_chunk.active_storage     | file.service_download_chunk.active_storage     | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_delete.active_storage             | file.service_delete.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_delete_prefixed.active_storage    | file.service_delete_prefixed.active_storage    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_exist.active_storage              | file.service_exist.active_storage              | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_url.active_storage                | file.service_url.active_storage                | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_mirror.active_storage             | file.service_mirror.active_storage             | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | service_update_metadata.active_storage    | file.service_update_metadata.active_storage    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | preview.active_storage                    | file.preview.active_storage                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | analyze.active_storage                    | file.analyze.active_storage                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-rails/lib/sentry/rails/tracing/active_storage_subscriber.rb#L7          |                                                            |
|                 | resque                                    | queue.resque                                   | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-resque/lib/sentry/resque.rb#L27                                         |                                                            |
|                 | db.redis.command                          | db.redis                                       | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-ruby/lib/sentry/redis.rb#L6                                             |                                                            |
|                 | rack.request                              | http.server                                    | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-ruby/lib/sentry/rack/capture_exceptions.rb#L66                          |                                                            |
|                 | sidekiq                                   | queue.sidekiq                                  | https://github.com/getsentry/sentry-ruby/blob/353a813378e708657ca83336947720406b4d9bc4/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L41             |                                                            |
| Laravel         |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | laravel.view                              | view.laravel                                   | https://github.com/getsentry/sentry-laravel/blob/afe35677784415dbbabd9d6be626948d739fc8aa/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php#L39                      |                                                            |
| Dart            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | serialize                                 | serialize.http.client + serialize.file.read    | https://github.com/getsentry/sentry-dart/blob/7987216d70e68ca0c3e58361bf48e6528f6392d1/dio/lib/src/sentry_transformer.dart#L17-L18                                    |                                                            |
| Cocoa           |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | db.query                                  | db.sql.query                                   | https://github.com/getsentry/sentry-cocoa/blob/91fc76f19bce100895028b52f642469698cd90ae/Sources/Sentry/include/SentryCoreDataTracker.h#L7                             | https://github.com/getsentry/sentry-cocoa/pull/2222        |
|                 | db.transaction                            | db.sql.transaction                             | https://github.com/getsentry/sentry-cocoa/blob/91fc76f19bce100895028b52f642469698cd90ae/Sources/Sentry/include/SentryCoreDataTracker.h#L9                             | https://github.com/getsentry/sentry-cocoa/pull/2222        |
| Java            |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | <graphql op name>                         | http.graphql.<op-name>                         | https://github.com/getsentry/sentry-java/blob/e2ea31c73c93aa587941cb7ea9254f853786db26/sentry-apollo/src/main/java/io/sentry/apollo/SentryApolloInterceptor.kt#L88    |                                                            |
|                 | <objectType>.<segment>                    | ???                                            | https://github.com/getsentry/sentry-java/blob/e2ea31c73c93aa587941cb7ea9254f853786db26/sentry-graphql/src/main/java/io/sentry/graphql/SentryInstrumentation.java#L136 |                                                            |

**Comment by AbhiPrasad** [comment]
Closing this issue as we've conducted the audit and made changes, and created sub issues in all the relevant SDKs that need changes.
