### ISSUE TITLE
Architecture Overview

### ISSUE THREAD

**Issue by joscha-alisch** [getsentry/develop#74]
Hi there, 
we have recently upgraded to sentry 10 and are a bit overwhelmed with the number of components that are now included with sentry. In order to better understand which service does what and to monitor it accordingly, it would be great to have some kind of overview of the architecture. This would be especially useful in regards to the various data stores/queues like kafka, rabbitmq, redis, etc.

It would be great if you could provide such an overview. In the best case, this could be a diagram of sorts, but just a written section would suffice as well probably.

**Comment by dcramer** [comment]
Would something like this suffice? https://github.com/getsentry/event-ingestion-graph/

We could embed it in the docs (or link to it)

**Comment by joscha-alisch** [comment]
That's exactly what I was looking for, thanks! I think a link to that would be a good addition to the docs.

**Comment by joscha-alisch** [comment]
To aid my personal understanding of this I created a little infographic and I thought I'd share it here in case it might help someone else :) 

If it is indeed a correct representation, feel free to use it however you see fit!

![sentry architecture](https://user-images.githubusercontent.com/9500791/86889678-6e1e6a00-c0fc-11ea-8db0-b677808b474c.png)

**Comment by untitaker** [comment]
hey @joscha-alisch, which tool did you use to create this graphic? That seems to be much nicer than what we can get done via mermaid.js and we're wondering if we could embed an editable version into the docs build system.

**Comment by joscha-alisch** [comment]
@untitaker I did it with [draw.io](http://draw.io/), not sure whether it's possible to include that in your build system. I attached the source file in case :) 


[sentry-drawio.zip](https://github.com/getsentry/develop/files/4896067/sentry-drawio.zip)

**Comment by untitaker** [comment]
Reopening this until we incorporate this chart

**Comment by untitaker** [comment]
Also quick note, relay + ingest-consumer are missing from that chart, as somebody on Discord pointed out.

**Comment by untitaker** [comment]
Decided to add multiple small graphs to the docs instead. Those can then be owned by respective teams, maybe. See #92.

The draw.io thing seems infeasible to maintain, unfortunately.
