### ISSUE TITLE
Document how BrowserTracing pageload captures Performance Entries

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/develop#797]
We leverage different performance entries like https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming and https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming to generate spans on a pageload transaction. 

We should document what Browser APIs we use and why so that user's get a better understanding of what is being tracked. We should also cover what heuristics we use to trim idle transactions.

Not sure if this lives in docs.sentry.io, develop.sentry.io or in the SDK repo itself.

**Comment by smeubank** [comment]
my 2 cents, this belongs in develop, and could reference in SDK docs for user that might want to know more

but typical users should not need to know how the internals product the magic 🪄
