### ISSUE TITLE
Profiling docs

### ISSUE THREAD

**Issue by vaind** [getsentry/develop#812]
The docs for the profiling product seem to be missing completely. It would be nice to have some intro how this fits in with other parts of SDKs, e.g. transactions as well as having format specification, similar to https://github.com/getsentry/develop/blob/master/src/docs/sdk/event-payloads/transaction.mdx

**Comment by AbhiPrasad** [comment]
@indragiek is this something we are thinking about? Would be great to have the format documented and SDK API there!

**Comment by AbhiPrasad** [comment]
With https://github.com/getsentry/develop/pull/841 and https://github.com/getsentry/develop/pull/872 getting merged in, going to close this for now.

@phacops feel free to re-open if there's more y'all are going to add.
